import { build } from 'esbuild';
import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
await build({entryPoints:['src/main/store.ts'],outfile:'build/electron/store-test.cjs',bundle:true,platform:'node',format:'cjs',external:['sql.js']});
const require=createRequire(import.meta.url),{Store}=require('../build/electron/store-test.cjs');
const folder=fs.mkdtempSync(path.resolve('tests/.store-'));
const wasm=path.resolve('node_modules/sql.js/dist/sql-wasm.wasm');
let s=new Store(folder);await s.open(wasm);
const client=s.saveClient({name:'Test client',currency:'USD'});
const project=s.saveProject({name:'Project',clientId:client.id,hourlyRateMinor:2550,currency:'USD'});
const tag=s.saveTag({name:'Design'});
const now=Date.now(),start=now-4*3600000;
const entry=s.saveEntry({projectId:project.id,startAt:start,endAt:start+3600000,note:'Example',billable:true,tagIds:[tag.id]});
assert.equal(s.rows('PRAGMA foreign_keys')[0].foreign_keys,1);
assert.throws(()=>s.transaction(()=>s.write('DELETE FROM projects WHERE id=?',[project.id])),/FOREIGN KEY/);
assert.equal(s.projects().length,1);
assert.throws(()=>s.saveEntry({projectId:null,startAt:start+30000,endAt:start+90000,tagIds:[]}),/overlaps/);
s.saveProject({...project,hourlyRateMinor:4000,currency:'EUR'});
s.saveEntry({...entry,note:'Edited note'});
assert.equal(s.entries()[0].hourlyRateMinor,2550);
s.saveSettings({senderName:'Test Sender'});
const invoice=s.createInvoice({clientId:client.id,currency:'USD',period:{startMs:start,endMs:now}});
assert.equal(invoice.total_minor,2550);
assert.throws(()=>s.transaction(()=>s.write('DELETE FROM invoices')),/cannot be deleted/);
const running=s.startTimer({projectId:null,startAt:now-2*60000,tagIds:[]});
s.db.close();s=new Store(folder);await s.open(wasm);
assert.equal(s.entries().find(e=>e.endAt===null).id,running.id);
s.stopTimer();assert.equal(s.entries().some(e=>e.endAt===null),false);
s.startTimer({projectId:null,tagIds:[]});s.stopTimer();assert.equal(s.entries().length,2);
s.transaction(()=>s.write('DELETE FROM tags WHERE id=?',[tag.id]));
assert.equal(s.rows('SELECT count(*) AS n FROM entry_tags')[0].n,0);
assert.equal(s.entries().length,2);
const count=s.clients().length,original=s.file;s.file=path.join(folder,'missing','invalid.sqlite');
assert.throws(()=>s.saveClient({name:'Must roll back'}));s.file=original;assert.equal(s.clients().length,count);
s.flush();assert.equal(s.rows('PRAGMA foreign_keys')[0].foreign_keys,1);s.db.close();
console.log('Store integration: persistence, recovery, cascade, rate snapshots, overlap, invoice and rollback checks passed.');
